export const AUTH = 'AUTH';
export const GET_SLIDES = 'GET_SLIDES';
export const GET_WEEKLY_NEWS = 'GET_WEEKLY_NEWS';
export const TOGGLE_WEEKLY_NEWS_POPUP = 'TOGGLE_WEEKLY_NEWS_POPUP';
export const RES_TOKEN = 'RESTORE_TOKEN';
export const UPDATE_FORM_DATA = 'UPDATE_FORM_DATA';
export const FORM_SUBMIT_FAILED = 'FORM_SUBMIT_FAILED';