const departments = [
{
    name: 'KHC',
    deptName: 'Khối Hành Chánh',
    primaryOwner: 'Vinh Sơn Bùi Anh Chương',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/ChuongBui.jpg',
    primaryOwnerPhone: '912-398-4981',
    primaryOwnerEmail: 'chuongbui@hvmatl.org',
    secondaryOwner: 'Anna Vũ Thùy Trang',
    secondaryOwnerTitle: 'Phó Khối',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/TrangVu.jpg',
    secondaryOwnerPhone: '678-906-1001',
    secondaryOwnerEmail: 'trang.t.vu@hvmatl.org',
},
{
    name: 'KDS',
    deptName: 'Khối Đời Sống',
    primaryOwner: 'Anna Lê Tuyết Mai',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/MaiLe.jpg',
    primaryOwnerPhone: '770-241-0264',
    primaryOwnerEmail: 'tuyetle@hvmatl.org',
    secondaryOwner: 'Martinô Nguyễn Ngọc Thành',
    secondaryOwnerTitle: 'Phó Khối',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/ThanhNguyen.jpg',
    secondaryOwnerPhone: '404-360-1362',
    secondaryOwnerEmail: 'thanh.ngoc.nguyenhvmatl.org',       
},
{
    name: 'KPT',
    deptName: 'Khối Phụng Tự',
    primaryOwner: 'Gioan Kim Khẩu Lê Kevin Tâm',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/TamLe.jpg',
    primaryOwnerPhone: '678-268-8891',
    primaryOwnerEmail: 'tamle@hvmatl.org',
    secondaryOwner: 'Anselmo Nguyễn Quốc Dũng',
    secondaryOwnerTitle: 'Phó Khối',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/DungNguyen.jpg',
    secondaryOwnerPhone: '404-483-7994',
    secondaryOwnerEmail: 'dung.quoc.nguyen@hvmatl.org',
},
{
    name: 'KTG',
    deptName: 'Khối Truyền Giáo',
    primaryOwner: 'Giuse Trần Khiêm Chánh',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/ChanhTran.jpg',
    primaryOwnerPhone: '678-234-6530',
    primaryOwnerEmail: 'chanhtran@hvmatl.org',
    secondaryOwner: 'Phêrô Nguyễn Hữu Đức',
    secondaryOwnerTitle: 'Phó Khối',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/DucNguyen.jpg',
    secondaryOwnerPhone: '678-640-6568',
    secondaryOwnerEmail: 'duc.huu.nguyen@hvmatl.org',
},
{
    name: 'KGD',
    deptName: 'Khối Giáo Dục',
    primaryOwner: 'Phaolô Nguyễn Chính',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/PaulNguyen.jpg',
    primaryOwnerPhone: '678-644-0853',
    primaryOwnerEmail: 'paul.chinh.nguyen@hvmatl.org',
    secondaryOwner: 'Têrêsa Nguyễn Lệ Thảo',
    secondaryOwnerTitle: 'Phó Khối',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/ThaoLe.jpg',
    secondaryOwnerPhone: '770-900-0769',
    secondaryOwnerEmail: 'lethao.theresa@hvmatl.org',
},
{
    name: 'KCS',
    deptName: 'Khối Cơ Sở',
    primaryOwner: 'Gioan Trình Ngọc Phúc',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/PhucTrinh.jpg',
    primaryOwnerPhone: '770-841-6107',
    primaryOwnerEmail: 'phuc.trinh@hvmatl.org',
    secondaryOwner: 'Giuse Lê Thức',
    secondaryOwnerTitle: 'Phó Khối',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/ThucLe.jpg',
    secondaryOwnerPhone: '404-644-8505',
    secondaryOwnerEmail: 'thucle@hvmatl.org', 
},
{
    name: 'KGQ',
    deptName: 'Khối Gây Quỹ',
    primaryOwner: 'Antôn Vũ Minh Tuấn',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/TuanVu.jpg',
    primaryOwnerPhone: '678-600-6038',
    primaryOwnerEmail: 'tuanvu@hvmatl.org',
    secondaryOwner: 'Micae Cao Hùng Anh',
    secondaryOwnerTitle: 'Phó Khối',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/AnhCao.jpg',
    secondaryOwnerPhone: '678-665-6189',
    secondaryOwnerEmail: 'anhcao@hvmatl.org',    
},
{
    name: 'KQT',
    deptName: 'Khối Quản Trị',
    primaryOwner: 'Phanxicô Xaviê Bùi Thịnh',
    primaryOwnerTitle: 'Trưởng Khối',
    primaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/thinhbui.png',
    primaryOwnerPhone: '678-799-1638',
    primaryOwnerEmail: 'thinh.bui@hvmatl.org',
    secondaryOwner: 'Lucia Lê Jennie',
    secondaryOwnerTitle: 'Quản Lý Văn Phòng',
    secondaryOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/JennieLe.jpg',
    secondaryOwnerPhone: '678-256-1314',
    secondaryOwnerEmail: 'jenniele@hvmatl.org',
    thirdOwner: 'Madalena Toyama Madalena ',
    thirdOwnerTitle: 'Thư Ký',
    thirdOwnerImg: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/img/core-img/NaMadalena.jpg',
    thirdOwnerPhone: '770-899-3548',
    thirdOwnerEmail: 'toyamam@hvmatl.org',   
}
];

export default departments;
