const departments = [
{
    name: 'Gioan Phạm Khoa Văn',
    deptAcronym: 'KHC',
    deptName: 'Khối Hành Chánh',
    title: 'Trưởng Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/VanPham.jpg',
    phone: '404-992-1122',
    email: 'van.k.pham@cttdvnatl.org',
},
{
    name: 'Anna Vũ Thùy Trang',
    deptAcronym: 'KHC',
    deptName: 'Khối Hành Chánh',
    title: 'Phó Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/TrangVu.jpg',
    phone: '678-906-1001',
    email: 'annavusss@gmail.com',
},
{
    name: 'Anna Lê Tuyết Mai',
    deptAcronym: 'KDS',
    deptName: 'Khối Đời Sống',
    title: 'Trưởng Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/MaiLe.jpg',
    phone: '770-241-0264',
    email: 'tuyetmai680@yahoo.com',
},
    name: 'Phêrô Hà Thanh Hùng',
    deptAcronym: 'KDS',
    deptName: 'Khối Đời Sống',    
    title: 'Phó Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/HungHa.jpg',
    phone: '770-542-9680',
    email: 'hathanhhung@yahoo.com',       
},
{
    name: 'Cecilia Lê Tú Anh',
    deptAcronym: 'KPT',
    deptName: 'Khối Phụng Tự',
    title: 'Trưởng Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/TuAnh.jpg',
    phone: '404-403-2763',
    email: 'TuAnh2003@cttdvnatl.org',
},
{
    name: 'Gioakim Lê Kevin Tâm',
    deptAcronym: 'KPT',
    deptName: 'Khối Phụng Tự',    
    title: 'Phó Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/TamLe.jpg',
    phone: '678-268-8891',
    email: 'Nam_viet911@yahoo.com',
},
{
    name: 'Giuse Nguyễn Quang Tấn',
    deptAcronym: 'KTG',
    deptName: 'Khối Truyền Giáo',
    title: 'Trưởng Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/TanNguyen.jpg',
    phone: '678-670-0817',
    email: 'tan.q.nguyen@cttdvnatl.org',
},
{
    name: 'Giuse Trần Khiêm Chánh',
    deptAcronym: 'KTG',
    deptName: 'Khối Truyền Giáo',    
    title: 'Phó Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/ChanhTran.jpg',
    phone: '678-234-6530',
    email: 'chanhvictor@yahoo.com',
},
{
    name: 'Phaolô Nguyễn Chinh Paul',
    deptAcronym: 'KGD',
    deptName: 'Khối Giáo Dục',
    title: 'Trưởng Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/PaulNguyen.jpg',
    phone: '678-644-0853',
    email: 'paul.chinh.nguyen@cttdvnatl.org',
},
{
    name: 'Theresa Nguyễn Lệ Thảo',
    deptAcronym: 'KGD',
    deptName: 'Khối Giáo Dục',    
    title: 'Phó Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/ThaoLe.jpg',
    phone: '770-900-0769',
    email: 'lethao.theresa@cttdvnatl.org',
},
{
    name: 'Gioan Phạm Thanh Tú',
    title: 'Trưởng Khối',
    deptAcronym: 'KCS',
    deptName: 'Khối Cơ Sở',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/TuPham.jpg',
    phone: '404-376-1336',
    email: 'ljohntupham@yahoo.com',
},
{
    name: 'Antôn Vũ Thanh',
    deptAcronym: 'KCS',
    deptName: 'Khối Cơ Sở',    
    title: 'Phó Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/ThanhVu.jpg',
    phone: '770-401-1916',
    email: 'tvu99@hotmail.com', 
},
{
    name: 'Antôn Vũ Minh Tuấn',
    deptAcronym: 'KGQ',
    deptName: 'Khối Gây Quỹ',
    title: 'Trưởng Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/TuanVu.jpg',
    phone: '678-600-6038',
    email: 'TuanVuCttdvn@gmail.com',
},
{
    name: 'Micae Cao Hùng Anh',
    deptAcronym: 'KGQ',
    deptName: 'Khối Gây Quỹ',    
    title: 'Phó Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/AnhCao.jpg',
    phone: '678-665-6189',
    email: 'CaoFinancial@gmail.com',    
},
{
    name: 'Giuse Vũ Văn Hưởng',
    deptAcronym: 'KQT',
    deptName: 'Khối Quản Trị',
    title: 'Trưởng Khối',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/HuongVu.jpg',
    phone: '704-726-6872',
    email: 'vuonthemove@charter.net',
},
{
    name: 'Lucia Lê Jennie',
    deptAcronym: 'KQT',
    deptName: 'Khối Quản Trị',    
    title: 'Quản Lý Văn Phòng',
    image: 'http://www.cttdvnatl.net/gallery/img/core-img/JennieLe.jpg',
    phone: '678-256-1314',
    email: 'JennieLe@cttdvnatl.org',
},
{
    name: 'Madalena Toyama Madalena ',
    deptAcronym: 'KQT',
    deptName: 'Khối Quản Trị',    
    thirdOwnerTitle: 'Thư Ký',
    thirdOwnerImg: 'ftp.cttdvnatl.net/img/core-img/NaMadalena.jpg',
    thirdOwnerPhone: '770-899-3548',
    thirdOwnerEmail: 'MadalenaMails@yahoo.com',   
}
];

export default departments;
