const history = [
    {
        significance:'two',
        year:'2019',
        title:'Thánh lễ Thánh Hiến nhà thờ mới được cử hành vào lễ Tạ Ơn (First Mass at New Church Celebrated on Thanksgiving)',
        image:'<img className="history-image" src="img/bg-img/hjnewchurch.jpg" width="40%" height="25%"></img>',
        imgsrc:'img/bg-img/hjnewchurch.jpg',
        imgheight:'20%',
        imgwidth:'32%',
        description:'Nhà thờ và bàn thờ được Đức Cha Joel M. Konzen giám quản Tông Tòa Tổng Giáo phận Atlanta chủ sự.',
        translate:" Dedication of church and altar presided by Bishop Joel M. Konzen Administrator of the Archdiocese of Atlanta"
    },
    {
        significance:'one',
        year:'2017',
        title: 'Khởi công xây dựng nhà thờ mới (Ground Breaking New Church)',
        image: '<img className="history-image" src="img/bg-img/khoicong.jpg" width="40%" height="25%"></img>',
        imgsrc:'img/bg-img/khoicong.jpg',
        imgheight:'20%',
        imgwidth:'30%',
        description:' Nghi thức khởi công xây dựng nhà thờ mới được chủ sự ngày 27 tháng 8. Việc đặt viên đá đầu tiên và khởi động xây dựng thánh đường là một ước ao từ lâu của giáo xứ.',
        translate:' Groundbreaking for new church. Blessed by Archbishop Wilton D. Gregory on Aug. 27, the huge stone and ceremonial groundbreaking marked another step toward the long-sought goal of the new church.'
    },
    {
        significance:'one',
        year:'2013',
        title:'Giáo xứ Việt Nam mới (New Vietnamese Parish)',
        image:'<img className="history-image" src="img/bg-img/hjchaTuan.jpg" width="30%" height="10%"/>',
        imgsrc:'img/bg-img/hjchaTuan.jpg',
        imgheight:'8%',
        imgwidth:'24%',
        description: 'Họ đạo được nâng lên hàng giáo xứ, trở thành giáo xứ thứ hai trong tổng giáo phận Atlanta. Cha Tuấn Trần trở thành Cha Chánh Xứ của họ đạo.',
        translate: 'The mission becomes the second Vietnamese parish in the archdiocese. Father Francis Tuan Tran becomes the parish pastor.',
    },
    {
        significance:'one',
        year:'2011',
        title: 'Mở rộng khuôn viên Giáo Xứ (Expanded Church Land)',
        image:'<img className="history-image" src="img/bg-img/expand.jpg" width="40%" height="25%"></img>',
        imgsrc:'img/bg-img/expand.jpg',
        imgheight:'20%',
        imgwidth:'30%',
        description:'Vào ngày 11 tháng 1 năm 2011, giáo xứ Thánh Tử Đạo Việt Nam đã hoàn tất việc mua khuôn viên mới rộng 9 mẫu. ',
        translate:'On January 11, 2011 the Archdiocese of Atlanta and our church, The Holy Martyrs of Vietnam Catholic Church, completed the purchase of the 9-acre property.'
    },
    {
        significance:'one',
        year:'2009',
        title:'Hội chợ mùa thu đầu tiên (First Fall Festival)',
        image:'<img className="history-image" src="img/bg-img/hjfall_fest.jpg" width="40%" height="25%"/>',
        imgsrc:'img/bg-img/hjfall_fest.jpg',
        imgheight:'20%',
        imgwidth:'32%',
        description:'Lễ Hội Mùa Thu được phát động vào cuối tuần ngày Lao Động để gây quỹ cho nhà thờ mới và tạo sinh hoạt cho cộng đồng.',
        translate:'The fall festival launched on Labor Day weekend to raise funds for the new and larger church for the growing community.'
    },
    {
        significance:'one',
        year:'2006',
        title:'Thánh lễ đầu tiên tại địa điểm nhà thờ mới (First Mass at New Church Site)',
        image:'<img className="history-image" src="img/bg-img/firstmass.jpg" width="30%" height="10%"/>',
        imgsrc:'img/bg-img/firstmass.jpg',
        imgheight:'8%',
        imgwidth:'24%',
        description:'Thánh Lễ tiếng Việt đầu tiên tại cơ xở mới họ đạo cùng những sinh hoạt tôn giáo và văn hóa khác. Lình Mục Phêrô Vũ Ngọc Đức nhận bài sai mới làm quản nhiệm họ đạo. Đức Tổng Giám Mục Wilton D. Gregory chủ sự tri thức Thánh Hiến Thánh Đường',
        translate:'The first Vietnamese Mass at the new facility, with other religious and cultural activities lead by Pastor Peter Vu Ngoc Duc. Consecrated Rite was celebrated by Archbishop Wilton D. Gregory'
    },
    {
        significance:'one',
        year:'2005',
        title: 'Khởi công tu sửa khu đất mới. (Renovations Begin)',
        image:'<img className="history-image" src="img/bg-img/renovation.jpg" width="40%" height="25%"></img>',
        imgsrc:'img/bg-img/renovation.jpg',
        imgheight:'20%',
        imgwidth: '30%',
        description: 'Khu đất mới được khởi công tu sửa',
        translate: 'Renovaton started on the new land'
    },
    {
        significance:'two',
        year:'2004',
        title:'Mua địa điểm xây dựng Thánh Đường. (Purchase Church Site)',
        image: '<img className="history-image" src="img/bg-img/purchase.jpg" width="40%" height="25%"></img>',
        imgsrc: 'img/bg-img/purchase.jpg',
        imgheight: '20%',
        imgwidth: '30%',
        description:'Mua cơ xở bán xe hơi Chevrolet với diện tích 7 mẫu và khu nhà tiên chế rộng 50,000 SF',
        translate:'Old Chevrolet car dealership with 7 acres of land and 50,000 SF buildings purchased for the new church'
    },
    {
        significance:'one',
        year:'2003',
        title:'Phước lành của Đức Tổng Giám mục (Blessing by the Archbishop)',
        image: '<img className="history-image" src="img/bg-img/ArchbishopJohnDonoghue.jpg" width="30%" height="10%"/>',
        imgsrc: 'img/bg-img/ArchbishopJohnDonoghue.jpg',
        imgheight: '8%',
        imgwidth: '24%',
        description:'Họ Đạo Các Thánh Từ Đạo Việt Nam được thành lập bởi Đức Tổng Giám Mục John F. Donoghue',
        translate:'Holy Vietnamese Martyrs parish consecrated by Archbishop John F. Donoghue'
    },
    {
        significance:'one',
        year:'2002',
        title:'Bắt đầu gây quỹ xây dựng Thánh Đường (Fundraising Begins)',
        image: '<img className="history-image" src="img/bg-img/fundrasing.jpg" width="40%" height="25%"></img>',
        imgsrc: 'img/bg-img/fundrasing.jpg',
        imgheight:'20%',
        imgwidth:'30%',
        description:'Thực hiện việc gây quỹ xây dựng Thánh Đường.',
        translate:'Fundraising begins for the new church.',
    },
    {
        significance:'two',
        year:'2001',
        title:'Giấy phép được cung cấp bởi Đức Tổng Giám Mục để bắt đầu gây quỹ (Permission given by Archbishop to start fundraising)',
        image: '<img className="history-image" src="img/bg-img/permission.jpg" width="40%" height="25%"></img>',
        imgsrc: 'img/bg-img/permission.jpg',
        imgheight: '20%',
        imgwidth: '30%',
        description:'Đức Tổng Giám Mục John F. Donoghue cho phép gây quỹ xây dựng.',
        translate:'The Building Fundraising license was granted by Archbishop John F. Donoghue, Archdiocese of Atlanta.'
    },
    {
        significance:'one',
        year:'1996',
        title:'Linh mục Phêrô Đức Vũ phong chức (Father Peter Duc Vu Ordained)',
        image:'<img className="history-image" src="img/bg-img/hjChaDuc.jpg" width="30%" height="25%"/>',
        imgsrc:'img/bg-img/hjChaDuc.jpg',
        imgheight:'20%',
        imgwidth:'24%',
        description:'Linh Mục Việt Nam đầu tiên thụ phong cho Tổng Giáo Phận Atlanta: Linh Mục Phêrô Vũ Ngọc Đức là Cha Phó Giáo Xứ Holy Cross, phục vụ đặc biệt cho người Việt Công Giáo tại giáo xứ.',
        translate:'First Vietnamese Priest to be ordained to the Archdiocese of Atlanta: Priest Peter Vu Ngoc Duc Deputy Holy Cross Parish and Pastoral Special for Vietnamese Catholics in the parish',
    },
    {
        significance:'one',
        year:'1996',
        title:'Đoàn Tôma Thiện was formed. (Youth Group Formed)',
        image:'<img className="history-image" src="img/bg-img/hjthieunhi.jpg" width="40%" height="25%"/>',
        imgsrc:'img/bg-img/hjthieunhi.jpg',
        imgheight:'20%',
        imgwidth:'32%',
        description:'Thiếu nhi do Anh Nguyễn Quốc Tuấn dẫn đầu với hơn 200 người tham dự.',
        translate:'The youth group was leaded by Mr. Nguyen Quoc Tuan with over 200 participants.',
    },
    {
        significance:'one',
        year:'1992',
        title:'Nguồn gốc của Giáo xứ Thánh Tử Đạo Việt Nam (Origin of Holy Vietnamese Martyrs Parish)',
        image:'<img className="history-image" src="img/core-img/SoMyHanhChaThanh.jpg" width="80%" height="25%"/>',
        imgsrc:'img/bg-img/SoMyHanhChaThanh.jpg',
        imgheight:'10%',
        imgwidth:'32%',
        description:'Thánh Lễ tiếng Việt dầu tiên tại Giáo Xứ Holy Cross, Cha Tuyên Úy Linh Mục Tôma Nguyễn Thái Thành và Sơ Christine Trương Mỹ Hạnh phụ trách.',
        translate:'Sister Christine Truong My Hanh, Sister of the Good Shepherd, begins gathering Vietnamese Catholics for Mass at Holy Cross Church, the second Sunday of every month.'
    }
]

export default history;
