const stJosephTeacherContent = [
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1a-nick-to.jpg',
        name: 'Thầy Nick Tô',
        email: 'nick.hoang.to@hvmatl.org',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1a-james-do.jpg',
        name: 'HSTT James Đỗ',
        email: ' james9108765@gmail.com',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1a-ngan-thanh-nguyen.jpg',
        name: 'Cô Ngân Thanh Nguyễn',
        email: 'lucynguyen0909@yahoo.com',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1b-truong-vu.jpg',
        name: 'Thầy Trường Vũ',
        email: 'jonnvu.pi@hvmatl.org',
        phone: 'Lớp 1B',
    },
    {   classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1b-cecilia-huynh.jpg',
        name: 'HSTT Cecilia Huynh',
        email: 'cchuynh12@gmail.com',
        phone: 'Lớp 1B',
    },
    {   classification: 'main-teacher',
    image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1b-arlene-dang.jpg',
    name: 'Cô Arlene Đặng',
    email: 'arlenedang81@gmail.com',
    phone: 'Lớp 1B',
},
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1c-truc-to.jpg',
        name: 'Cô Trúc Tô',
        email: 'trucjennifer@gmail.com',
        phone: 'Lớp 1C',
    },
    {   classification: 'main-teacher',
    image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1c-patrick-do.jpg',
    name: 'HSTT Patrick Đỗ',
    email: 'chinglao21@gmail.com',
    phone: 'Lớp 1C',
},
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-1c-sarah-dang.jpg',
        name: 'Cô Sarah Võ Đặng',
        email: 'sarahvdang@gmail.com',
        phone: 'Lớp 1C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2a-vy-do.jpg',
        name: 'Cô Vy Đỗ',
        email: 'anna.vy.do@hvmatl.org',
        phone: 'Lớp 2A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2a-ngoc-tran.jpg',
        name: 'Cô Ngọc Trần',
        email: 'ngoctrantoday@gmail.com',
        phone: 'Lớp 2A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2b-hang-ngo.jpg',
        name: 'Cô Hằng Mỹ H. Ngô',
        email: 'hang.ngo@hvmatl.org',
        phone: 'Lớp 2B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2b-tra-nguyen.jpg',
        name: 'Cô Trà Kim Nguyễn',
        email: 'tra.kim.nguyen@hvmatl.org',
        phone: 'Lớp 2B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2c-khanh-linh-nguyen.jpg',
        name: 'Cô Khánh Linh Nguyễn',
        email: 'mckhanhlinhusa@gmail.com',
        phone: 'Lớp 2C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2c-adam-le.jpg',
        name: 'HSTT Adam Lê',
        email: 'leadam20@gmail.com',
        phone: 'Lớp 2C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2c-antony-huynh.jpg',
        name: 'HT Antony Huỳnh',
        email: 'fatherthomashuynh490@gmail.com',
        phone: 'Lớp 2D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-2d-teresa-ha.jpg',
        name: 'HSTT Teresa Hà',
        email: 'teresaha2006@gmail.com',
        phone: 'Lớp 2D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3a-tu-nguyen.jpg',
        name: 'Thầy Tú Tuấn Nguyễn',
        email: 'francis.tu.nguyen@hvmatl.org',
        phone: 'Lớp 3A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3a-linh-tran.jpg',
        name: 'Cô Linh Trần',
        email: 'catherine.linh.tran@hvmatl.org',
        phone: 'Lớp 3A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3b-thao-nguyen.jpg',
        name: 'Cô Thảo Thanh Nguyễn',
        email: 'anna-maria-thao.nguyen@hvmatl.org',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3b-khanh-thuy-tran.jpg',
        name: 'Cô Khanh Thủy Trần',
        email: 'khanh.thuy.tran@hotmail.com',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3b-khanh-trang-tran.jpg',
        name: 'HSTT Khánh-Trang Trần',
        email: 'atrangtranalt@gmail.com',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3c-thao-dinh.jpg',
        name: 'Cô Thảo Thu Đinh',
        email: 'thuthao.dinh@hvmatl.org',
        phone: 'Lớp 3C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3c-hien-le.jpg',
        name: 'Cô Hiền Diệu Lê',
        email: 'hienledn@yahoo.com',
        phone: 'Lớp 3C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3d-an-nguyen.jpg',
        name: 'HT Hồng Ân Nguyễn',
        email: 'jomar.hongan.nguyen@hvmatl.org',
        phone: 'Lớp 3D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3d-hien-vo.jpg',
        name: 'HT Elizabeth Hien Vo',
        email: 'vothikimhien0101@gmail.com',
        phone: 'Lớp 3D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3e-diem-nguyen.jpg',
        name: 'Cô Diễm Nguyễn',
        email: 'Diem.nguyen_23@yahoo.com',
        phone: 'Lớp 3E',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-3e-timothy-truong.jpg',
        name: 'Thầy Timothy Trương',
        email: 'timothytruong2000@gmail.com',
        phone: 'Lớp 3E',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-4a-marian-phan.jpg',
        name: 'HT Marian Phan',
        email: 'marian.phan@hvmatl.org',
        phone: 'Lớp 4A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-4a-jared-nguyen.jpg',
        name: 'Thầy Jared Nguyễn ',
        email: 'nguyenjare2001@gmail.com ',
        phone: 'Lớp 4A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-4b-christopher-nguyen.jpg',
        name: 'HT Christopher Nguyễn',
        email: 'christopher.nguyen@hvmatl.org',
        phone: 'Lớp 4B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-4b-judy-ngo.jpg',
        name: 'Cô Judy Ngô',
        email: 'judy.ngo678@gmail.com',
        phone: 'Lớp 4B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-4c-ngoc-mai.jpg',
        name: 'Thầy Ngọc Viết Mai',
        email: 'ngoc.viet.mai@hvmatl.org',
        phone: 'Lớp 4C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-4c-dieu-nguyen.jpg',
        name: 'Cô Diệu Thu Nguyễn',
        email: 'dieu.thu.nguyen@hvmatl.org',
        phone: 'Lớp 4C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-5a-andrew-nguyen.jpg',
        name: 'HT Andrew Hữu Nguyễn',
        email: 'andrew.huu.nguyen@hvmatl.org',
        phone: 'Lớp 5A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-5a-thu-nguyen.jpg',
        name: 'Cô Thu Nguyễn',
        email: 'thu.nguyen@hvmatl.org',
        phone: 'Lớp 5A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-5a-linh-nguyen.jpg',
        name: 'Cô Linh Thủy Nguyễn',
        email: 'linhthuyn73@gmail.com',
        phone: 'Lớp 5A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-5b-steven-nguyen.jpg',
        name: 'HT Steven Nguyễn',
        email: 'joseph.steven.nguyen@hvmatl.org',
        phone: 'Lớp 5B',
    },    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-5b-kenny-pham.jpg',
        name: 'HT Kenny Phạm',
        email: 'kennypham9397@gmail.com',
        phone: 'Lớp 5B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-5c-rachel-le.jpg',
        name: 'Cô Rachel Quý lê',
        email: 'rle4.usa@gmail.com',
        phone: 'Lớp 5C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-5c-tuyet-nguyen.jpg',
        name: 'Cô Tuyết Ánh Nguyễn',
        email: 'eyebest2000@yahoo.com',
        phone: 'Lớp 5C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-6a-linh-ho.jpg',
        name: 'Cô Linh Thùy Hồ',
        email: 'thuy.linh.ho@hvmatl.org',
        phone: 'Lớp 6A',
    },

    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-6a-hoang-bui.jpg',
        name: 'Thầy Hoàng Bùi',
        email: 'hbui5580@gmail.com',
        phone: 'Lớp 6A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-6b-sang-ho.jpg',
        name: 'Thầy Sang Hồ',
        email: 'sang_hs1@yahoo.com',
        phone: 'Lớp 6B',
    }, 
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-6b-angela-nguyen.jpg',
        name: 'HT Angela Tiên Nguyễn',
        email: 'angelatn.4080@gmail.com',
        phone: 'Lớp 6B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-6c-brian-luong.jpg',
        name: 'Thầy Brian Lương',
        email: 'hoangnhut9755@gmail.com',
        phone: 'Lớp 6C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-6c-dang-tran.jpg',
        name: 'Cô Linh Đan Huỳnh Trần',
        email: 'linhdan1291@gmail.com',
        phone: 'Lớp 6C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-7a-brian-nguyen.jpg',
        name: 'Thầy Brian H. Nguyễn',
        email: 'brian.hoang.nguyen@hvmatl.org',
        phone: 'Lớp 7A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-7a-thuy-linh-nguyen.jpg',
        name: 'Cô Thùy Linh Nguyễn',
        email: 'thuylinh.le.nguyen@hvmatl.org',
        phone: 'Lớp 7A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-7b-son-tran.jpg',
        name: 'Thầy Sơn Trần',
        email: 'tranm2013@gmail.com',
        phone: 'Lớp 7B',
    },    
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-7b-thien-tu-nhat-nguyen.jpg',
        name: 'Cô Thiên Tú Nhật Nguyễn',
        email: 'thientunguyen86@yahoo.com',
        phone: 'Lớp 7B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-7b-kelvin-vu.jpg',
        name: 'HT Kelvin Vũ',
        email: 'lkelvinvu112@gmail.com',
        phone: 'Lớp 7C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-7c-jennifer-phuong-pham.jpg',
        name: 'HT Jennifer Phương Phạm',
        email: 'jp53091@uga.edu',
        phone: 'Lớp 7C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-8a-an-lam.jpg',
        name: 'Thầy Lâm An',
        email: 'lamangq74@yahoo.com',
        phone: 'Lớp 8A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-8a-thuy-thanh-tran.jpg',
        name: 'Cô Thủy Thanh Nguyễn',
        email: 'catarina.thuy.tran@hvmatl.org',
        phone: 'Lớp 8A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-8b-nghiem-trang.jpg',
        name: 'Cô Trang Nghiêm',
        email: 'tnghiem@hvmalt.org',
        phone: 'Lớp 8B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-8c-nathan-an.jpg',
        name: 'HT Nathan An',
        email: 'nathanan007@gmail.com',
        phone: 'Lớp 8C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-8c-cuc-nguyen.jpg',
        name: 'Cô Cúc Nguyễn',
        email: 'socnau143@yahoo.com',
        phone: 'Lớp 8C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9a-steven-nguyen.jpg',
        name: 'HT Steven Trương Nguyễn',
        email: 'steven.truong.nguyen@hvmatl.org',
        phone: 'Lớp 9A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9ca-hiep-le.jpg',
        name: 'Thầy Hiệp Lê',
        email: 'hiep.le@hvmatl.org',
        phone: 'Lớp 9A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9b-suong-ho.jpg',
        name: 'Cô Sương Cát Hồ',
        email: 'hocatsuong@gmail.com',
        phone: 'Lớp 9B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9b-thao-ngo.jpg',
        name: 'Cô Thảo Xuân Ngô',
        email: 'xuan.thao.ngo@hvmatl.org',
        phone: 'Lớp 9B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9c-su-le.jpg',
        name: 'Thầy Sứ Quang Lê',
        email: 'su.quang.le@hvmatl.org',
        phone: 'Lớp 9C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9c-trang-dang.jpg',
        name: 'Cô Trang Đặng',
        email: 'trangdang04@yahoo.com',
        phone: 'Lớp 9C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9d-bich-dao.jpg',
        name: 'Thầy Bích Đào',
        email: 'bich.dao@hvmatl.org',
        phone: 'Lớp 9D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-9d-diem-nguyen.jpg',
        name: 'Cô Diễm L. Nguyễn',
        email: 'diem.l.nguyen@hvmatl.org',
        phone: 'Lớp 9D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-10a-michelle-vu.jpg',
        name: 'Cô Michelle Vũ',
        email: 'ha.vu012@gmail.com',
        phone: 'Lớp 10A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-10a-loan-vu.jpg',
        name: 'Cô Loan Vũ',
        email: 'loan.vu@hvmatl.org',
        phone: 'Lớp 10A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-10b-hanson-hoang.jpg',
        name: 'HT Hanson Hoàng',
        email: 'hhoang61@gmail.com',
        phone: 'Lớp 10B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-10b-hien-pham.jpg',
        name: 'Cô Hiền Phạm',
        email: 'hien.pham@hvmatl.org',
        phone: 'Lớp 10B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-10c-jack-nguyen.jpg',
        name: 'HT Jack Nguyễn',
        email: 'jack.nguyen@hvmatl.org',
        phone: 'Lớp 10C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-10c-danny-dang-huynh.jpg',
        name: 'HT Dang Danny Huỳnh',
        email: 'danny.hai.huynh@hvmatl.org',
        phone: 'Lớp 10C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-hs1-kevin-nguyen.jpg',
        name: 'HT Kevin Nguyễn',
        email: 'kevin.bt.nguyen@hvmatl.org',
        phone: 'Hiệp Sĩ I',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-hs1-vu-hoang.jpg',
        name: 'HT Vũ Hoàng',
        email: 'vhoang92@gmail.com',
        phone: 'Hiệp Sĩ I',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-hs2-ha-ho.jpg',
        name: 'Thầy Hà Hồ',
        email: 'ho.ha@hvmatl.org',
        phone: 'Hiệp Sĩ II',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-hs2-andrew-do.jpg',
        name: 'HT Andrew Đỗ',
        email: 'itsandrewdo30@gmail.com',
        phone: 'Hiệp Sĩ II',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2024-25-teachers/2024-25-hs2-louis-ho.jpg',
        name: 'HT Louis Hồ',
        email: 'louis.hieu.ho@hvmatl.org',
        phone: 'Hiệp Sĩ II',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-samantha-nguyen.jpg',
        name: 'Đoàn Trưởng',
        email: 'Trưởng Samantha Nguyễn',
        phone: 'samantha.nguyen20@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-mary-vu.jpg',
        name: 'Phó Quản Trị',
        email: 'Trưởng Mary Vũ',
        phone: 'm.vu637@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-hanson-hoang.jpg',
        name: 'Phó Nghiêm Huấn',
        email: 'Trưởng Hanson Hoàng',
        phone: 'hhoang61@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-dalena-nguyen.jpg',
        name: 'Thư Ký',
        email: 'Trưởng Dalena Nguyễn',
        phone: 'dalena.nguyenad@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-dung-phan.jpg',
        name: 'Thủ Quỹ',
        email: 'Trưởng Kim Dung Phan',
        phone: 'trinhdung2k@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-thanh-le.jpg',
        name: 'Trưởng Ban Trợ Tá',
        email: 'Trưởng Thái Thành Lê',
        phone: 'thanhle2@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-kathleen-nguyen.jpg',
        name: 'Ngành Trưởng Ngành Ấu',
        email: 'Trưởng Kathleen Nguyễn',
        phone: 'kathleen.phuong.nguyen@hvmatl.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-whitney-tran.jpg',
        name: 'Ngành Phó Ngành Ấu',
        email: 'Trưởng Whitney Trần',
        phone: 'whitney_tran2018@yahoo.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-jessie-hoang.jpg',
        name: 'Ngành Trưởng Ngành Thiếu',
        email: 'Trưởng Jessie Hoàng',
        phone: 'jessiehoang2175@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-dennis-le.jpg',
        name: 'Ngành Phó Ngành Thiếu',
        email: 'Trưởng Dennis Lê',
        phone: 'dennis.le900@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-tony-ho.jpg',
        name: 'Ngành Trưởng Ngành Nghĩa',
        email: 'Trưởng Tony Hồ',
        phone: 't0nythetigg3r@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-victor-nguyen.jpg',
        name: 'Ngành Phó Ngành Nghĩa',
        email: 'Trưởng Victor Nguyễn',
        phone: 'nthang2444@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-khoa-do.jpg',
        name: 'Ngành Trưởng Ngành Hiệp ',
        email: 'Trưởng Khoa Đỗ',
        phone: 'kduydo@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-mary-le.jpg',
        name: 'Ngành Phó Ngành Hiệp',
        email: 'Trưởng Mary Lê',
        phone: 'lucia.mary.le@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-kevin-nguyen.jpg',
        name: 'Ủy Viên Phụng Vụ',
        email: 'Trưởng Kevin Nguyễn',
        phone: 'kevin.bt.nguyen@hvmatl.org',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-joseph-nguyen.jpg',
        name: 'Ủy Viên Thông Tin',
        email: 'Trưởng Joseph Nguyễn',
        phone: 'joseph.nguyen@hvmatl.org',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-phuong-nguyen.jpg',
        name: 'Ủy Viên Giao Tế',
        email: 'Trưởng Phương A. Nguyễn',
        phone: 'cuoi99@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-davis-nguyen.jpg',
        name: 'Ủy Viên Kỹ Thuật',
        email: 'Trưởng Davis Nguyễn',
        phone: 'davisngn2@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-lisa-nguyen.jpg',
        name: 'Ủy Viên Điều Phó Nội Vụ',
        email: 'Trưởng Lisa Nguyễn',
        phone: 'lisan0596@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-hai-huynh.jpg',
        name: 'Ủy Viên Gây Quỹ',
        email: 'Trưởng Hải Huỳnh',
        phone: 'hhoang61@gmail.com',
    },
    {   
        classification: 'tntt-rep',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-nghi-dinh.jpg',
        name: 'Ủy Viên Xã Hội',
        email: 'HSTT Nghi Đinh',
        phone: 'dinhhoanggianghi@gmail.com',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-1a-thy-pham.jpg',
        name: 'HSTT Thy Phạm',
        email: 'ptkimthy0207@gmail.com',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-1a-thi-nguyen.jpg',
        name: 'HSTT Thi Vũ Nguyễn',
        email: 'thivnguyen1411@gmail.com',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-1b-cecilia-huynh.jpg',
        name: 'HSTT Cecilia Huỳnh',
        email: 'huynhcecilia112@gmail.com',
        phone: 'Lớp 1B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-1b-quynh-nguyen.jpg',
        name: 'HSTT Anh Q. Nguyễn',
        email: 'anhnwin2407@gmail.com',
        phone: 'Lớp 1B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-1c-kazumi-fuji.jpg',
        name: 'HSTT Kazumi Fuji ',
        email: 'kazumi03fuji@gmail.com',
        phone: 'Lớp 1C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-2a-emily-tran.jpg',
        name: 'HSTT Emily Trần',
        email: 'its.emily.tran17@gmail.com',
        phone: 'Lớp 2A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-2a-luke-nguyen.jpg',
        name: 'HSTT Luke Nguyễn',
        email: 'lukenguyen2002@hotmail.com',
        phone: 'Lớp 2A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-2b-emily-freestone.jpg',
        name: 'HSTT Emily Freestone',
        email: 'freestone.emily@gmail.com',
        phone: 'Lớp 2C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-2b-antony-huynh.jpg',
        name: 'HT Antony Huỳnh',
        email: 'fatherthomashuynh490@gmail.com',
        phone: 'Lớp 2B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-2c-marian-phan.jpg',
        name: 'HT Marian Phan',
        email: 'marian.phan@hvmatl.org',
        phone: 'Lớp 2C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-2d-angela-nguyen.jpg',
        name: 'HT Angela Tiên Nguyễn',
        email: 'angelatn.4080@gmail.com',
        phone: 'Lớp 2D',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-3a-nhat-nguyen.jpg',
        name: 'HT Nhật Nguyễn',
        email: 'nvn32904@gmail.com',
        phone: 'Lớp 3A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-3a-nghi-dinh.jpg',
        name: 'HSTT Nghi Đinh',
        email: 'dinhhoanggianghi@gmail.com',
        phone: 'Lớp 3A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-3b-davis-nguyen.jpg',
        name: 'HT Davis Nguyễn',
        email: 'davisngn2@gmail.com',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-3b-hien-vo.jpg',
        name: 'HT Elizabeth Hien Vo',
        email: 'vothikimhien0101@gmail.com',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-3c-tommy-nguyen.jpg',
        name: 'HSTT Tommy Nguyễn',
        email: 'tnguy243@gmail.com',
        phone: 'Lớp 3C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-3d-an-nguyen.jpg',
        name: 'HT Hồng Ân Nguyễn',
        email: 'jomar.hongan.nguyen@hvmatl.org',
        phone: 'Lớp 3D',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-4a-alex-nguyen.jpg',
        name: 'HT Alex Hiếu Nguyễn',
        email: 'alexnguyen22@gmail.com',
        phone: 'Lớp 4A',
    }, 
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-4a-julia-phan.jpg',
        name: 'HSTT Julia Phan',
        email: 'jnp12344@gmail.com',
        phone: 'Lớp 4A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-4b-uyen-chu.jpg',
        name: 'HT Uyên Chu',
        email: 'uyen.chu@hvmatl.org',
        phone: 'Lớp 4B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-4b-khanh-nguyen.jpg',
        name: 'HT Khánh Nguyễn',
        email: 'khnguyen0623@gmail.com',
        phone: 'Lớp 4B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-4c-christopher-nguyen.jpg',
        name: 'HT Christopher Nguyễn',
        email: 'chris.tu.n.alt@@gmail.com',
        phone: 'Lớp 4C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-4c-andrew-nguyen.jpg',
        name: 'HT Andrew Nguyễn',
        email: 'andrew.huu.nguyen@hvmatl.org',
        phone: 'Lớp 4C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-5a-felix-le.jpg',
        name: 'HSTT Felix Lê',
        email: 'loclhf@gmail.com',
        phone: 'Lớp 5A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-5a-emily-nguyen.jpg',
        name: 'HT Emily Nguyễn',
        email: 'emilylnguyen28@gmail.com',
        phone: 'Lớp 5A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-5b-trina-pham.jpg',
        name: 'HSTT Trina Trinh Phạm',
        email: '17trinaapham@gmail.com',
        phone: 'Lớp 5B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-5c-tan-nguyen.jpg',
        name: 'HT Tân Nguyễn',
        email: 'tan.t.nguyen00@gmail.com',
        phone: 'Lớp 5C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-6a-steven-dang.jpg',
        name: 'HSTT Steven Đặng',
        email: 'stevendang99@gmail.com',
        phone: 'Lớp 6A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-6b-laura-huynh.jpg',
        name: 'HSTT Laura Nhi Huỳnh',
        email: 'huynhlaura2000@gmail.com',
        phone: 'Lớp 6B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-6c-michael-nguyen.jpg',
        name: 'HSTT Michael Vũ',
        email: 'michaelvu222@gmail.com',
        phone: 'Lớp 6C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-7a-bryan-nguyen.jpg',
        name: 'HT Bryan Nguyễn',
        email: 'nguyenbryan97@gmail.com',
        phone: 'Lớp 7A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-7a-heather-nguyen.jpg',
        name: 'HSTT Heather Nguyễn',
        email: 'hedawin16@gmail.com',
        phone: 'Lớp 7A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-7b-christina-tran.jpg',
        name: 'HSTT Christina Trần',
        email: 'tranji1@gmail.com',
        phone: 'Lớp 7B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-8a-nathan-an.jpg',
        name: 'HSTT Nathan An',
        email: 'nathanan007@gmail.com',
        phone: 'Lớp 8A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-8c-richard-ngo.jpg',
        name: 'HT Richard Ngô',
        email: '_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _',
        phone: 'Lớp 8A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-8c-alex-ngo.jpg',
        name: 'HSTT Alexander Ngô',
        email: 'ngo.alex011@gmail.com',
        phone: 'Lớp 8C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-8d-christopher-nguyen.jpg',
        name: 'HT Christopher Nguyễn',
        email: 'christopher.nguyen@hvmatl.org',
        phone: 'Lớp 8D',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-8d-viet-tran.jpg',
        name: 'TT Việt Trần',
        email: '_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _',
        phone: 'Lớp 8D',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-9a-alber-pham.jpg',
        name: 'HT Albert Phạm',
        email: 'albert.pham@hvmatl.org',
        phone: 'Lớp 9A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-9b-steven-nguyen.jpg',
        name: 'HSTT Steven Nguyễn',
        email: 'steventnguyen234@yahoo.com',
        phone: 'Lớp 9B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-9c-thomas-vo.jpg',
        name: 'HSTT Thomas Võ',
        email: 'thomas.vo@hvmatl.org',
        phone: 'Lớp 9C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-9c-thanh-le.jpg',
        name: 'TT Thành Lê',
        email: 'thanhle2@gmail.com',
        phone: 'Lớp 9C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-9d-phong-nguyen.jpg',
        name: 'TT Phong Nguyễn',
        email: '_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _',
        phone: 'Lớp 9D',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-10a-jack-nguyen.jpg',
        name: 'HT Jack Nguyễn',
        email: 'jack.nguyen@hvmatl.org',
        phone: 'Lớp 10A',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-10b-jack-do.jpg',
        name: 'HSTT Jack Đỗ',
        email: 'jack.duc.do@hvmatl.org',
        phone: 'Lớp 10B',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-10c-michelle-vu.jpg',
        name: 'Cô Michelle Vũ',
        email: 'ha.vu012@gmail.com',
        phone: 'Lớp 10C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-10c-duc-nguyen.jpg',
        name: 'HT Đức Nguyễn',
        email: 'duc.huu.nguyen@hvmatl.org',
        phone: 'Lớp 10C',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-10d-thanh-ly.jpg',
        name: 'HT Thành Lý',
        email: 'thanh.ly@hvmatl.org',
        phone: 'Lớp 10D',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-10d-thao-nguyen.jpg',
        name: 'HT Thảo Thu Nguyễn',
        email: 'thao.thu.nguyen@hvmatl.org',
        phone: 'Lớp 10D',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-hs1-hai-huynh.jpg',
        name: 'HT Hải Huỳnh',
        email: 'ayohai1207@gmail.com',
        phone: 'Lớp Hiệp Sĩ 1',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-hs1-andrew-do.jpg',
        name: 'HT Andrew Đỗ',
        email: 'itsandrewdo30@gmail.com',
        phone: 'Lớp Hiệp Sĩ 1',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-hs1-kristy-nguyen.jpg',
        name: 'HT Kristy Nguyễn',
        email: 'kristy.nguyen@veym.net',
        phone: 'Lớp Hiệp Sĩ 1',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-hs2-long-huynh.jpg',
        name: 'HT Long Huỳnh',
        email: 'longhuynh741@yahoo.com',
        phone: 'Lớp Hiệp Sĩ 2',
    },
    {   
        classification: 'children-eucharist',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-tntt-hs2-andy-hoang.jpg',
        name: 'HT Andy Hoàng',
        email: 'abh824@gmail.com',
        phone: 'Lớp Hiệp Sĩ 2',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-ha-ho.jpg',
        name: 'Thầy Hà Hồ',
        email: 'ho.ha4113@outlook.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-chau-ngo.jpg',
        name: 'Cô Châu Ngô',
        email: 'pearlga70@yahoo.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-hung-vo.jpg',
        name: 'Thầy Hưng Đỗ',
        email: 'hdo29@hotmail.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-amy-ho.jpg',
        name: 'Cô Amy Hồ',
        email: 'ho824538@gmail.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-kien-vo.jpg',
        name: 'Thầy Kiên Võ',
        email: 'tienkienvo@yahoo.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-loan-nguyen.jpg',
        name: 'Cô Loan Nguyễn',
        email: 'ngoc.loan@hotmail.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-nguyen-luu.jpg',
        name: 'Thầy Nguyên Lưu',
        email: 'nluu1972@yahoo.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-linh-nguyen.jpg',
        name: 'Cô Linh Nguyễn',
        email: 'nguyenvtm22@gmail.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-thanh-tran.jpg',
        name: 'Thầy Thành Trần',
        email: 'myvy2003@gmail.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-tam-nguyen.jpg',
        name: 'Cô Tâm Nguyễn',
        email: 'tamthibangnguyen@yahoo.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-thuy-ho.jpg',
        name: 'Thầy Thủy Hồ',
        email: 'holapxuan@yahoo.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-thao-pham.jpg',
        name: 'Cô Thảo Phạm',
        email: 'thaotu20062003@yahoo.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-tuan-nguyen.jpg',
        name: 'Thầy Tuấn Nguyễn',
        email: 'tuan@swiftatlanta.com',
        phone: '',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.s3.us-east-2.amazonaws.com/gallery/kgd/giaoly/2023-24-gl-p-thuy-tran.jpg',
        name: 'Cô Thủy Trần',
        email: 'bichthuytran1607@yahoo.com',
        phone: '',
    },
]

export default stJosephTeacherContent;