const stJosephTeacherContent = [
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-1a-01.jpg',
        name: 'HT Nguyễn Thu Thảo',
        email: 'thao.thu.nguyen@hvmatl.org',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-1a-02.jpg',
        name: 'HT Thành Lý',
        email: 'thanh.ly@hvmatl.org',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-1a-03.jpg',
        name: 'Cô Ngọc Trần',
        email: 'ngoctrantoday@gmail.com',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-1a-04.jpg',
        name: 'Cô Hà Thứy',
        email: 'hathuy08@yahoo.com',
        phone: 'Lớp 1A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-1b-01.jpg',
        name: 'Thầy Nick Tô',
        email: 'nick.hoang.to@hvmatl.org',
        phone: 'Lớp 1B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-1b-02.jpg',
        name: 'Cô Trần Linh Huỳnh',
        email: 'linhdan1291@gmail.com',
        phone: 'Lớp 1B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2a-01.jpg',
        name: 'Cô Thảo Xuân Ngô',
        email: 'xuan.thao.ngo@hvmatl.org',
        phone: 'Lớp 2A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2a-02.jpg',
        name: 'Cô Quyên Phương Đào',
        email: 'queeniedao1011@gmail.com',
        phone: 'Lớp 2A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2b-01.jpg',
        name: 'Cô Hằng Mỹ H. Ngô',
        email: 'hang.ngo@hvmatl.org',
        phone: 'Lớp 2B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2b-02.jpg',
        name: 'Cô Trà Kim Nguyễn',
        email: 'tra.kim.nguyen@hvmatl.org',
        phone: 'Lớp 2B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2c-01.jpg',
        name: 'Cô Vy Đỗ',
        email: 'anna.vy.do@hvmatl.org',
        phone: 'Lớp 2C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2c-02.jpg',
        name: 'Cô Thư Trần',
        email: 'thu.tran@hvmatl.org',
        phone: 'Lớp 2C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2d-01.jpg',
        name: 'HT Uyên Chu',
        email: 'uyen.chu@hvmatl.org',
        phone: 'Lớp 2D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-2d-02.jpg',
        name: 'HT Khánh Nguyễn',
        email: 'khanh.nguyen@hvmatl.org',
        phone: 'Lớp 2D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3a-01.jpg',
        name: 'Cô Diệu Thu Nguyễn',
        email: 'dieu.thu.nguyen@hvmatl.org',
        phone: 'Lớp 3A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3a-02.jpg',
        name: 'Thầy Trường Vũ',
        email: 'jonnvu.pi@hvmatl.org',
        phone: 'Lớp 3A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3b-01.jpg',
        name: 'Cô Hồng R. Freestone',
        email: 'hong.rose.freestone@hvmatl.org',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3b-02.jpg',
        name: 'Cô Emily Freestone',
        email: 'freestone.emily@gmail.com',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3b-03.jpg',
        name: 'Cô Christina Trần',
        email: 'tranji@gmail.com',
        phone: 'Lớp 3B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3c-01.jpg',
        name: 'Cô Thảo Thu Đinh',
        email: 'thuthao.dinh@hvmatl.org',
        phone: 'Lớp 3C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3c-02.jpg',
        name: 'Cô Hiên Diệu Lê',
        email: 'hienledn@yahoo.com',
        phone: 'Lớp 3C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3d-01.jpg',
        name: 'Cô Thảo Thanh Nguyễn',
        email: 'anna-maria-thao.nguyen@hvmatl.org',
        phone: 'Lớp 3D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-3d-02.jpg',
        name: 'Cô Tracy MyTuyet Võ',
        email: 'traceyvo27@yahoo.com',
        phone: 'Lớp 3D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-4a-01.jpg',
        name: 'Cô Diễm Nguyễn',
        email: 'Diem.nguyen_23@yahoo.com',
        phone: 'Lớp 4A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-4a-02.jpg',
        name: 'HT Julie Nguyễn',
        email: 'julie.lamthanh.nguyen@hvmatl.org',
        phone: 'Lớp 4A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-4b-01.jpg',
        name: 'Thầy Tú Tuấn Nguyễn',
        email: 'francis.tu.nguyen@hvmatl.org',
        phone: 'Lớp 4B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-4b-02.jpg',
        name: 'Cô Trang Ngọc Võ',
        email: 'trang12233@gmail.com',
        phone: 'Lớp 4B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-4c-01.jpg',
        name: 'HSTT Christopher Nguyễn',
        email: 'christopher.nguyen@hvmatl.org',
        phone: 'Lớp 4C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-4c-02.jpg',
        name: 'HT Nhật Nguyễn',
        email: 'nhat.harry.nguyen@hvmatl.org',
        phone: 'Lớp 4C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-5a-01.jpg',
        name: 'Cô Thu Nguyễn',
        email: 'thu.nguyen@hvmatl.org',
        phone: 'Lớp 5A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-5a-02.jpg',
        name: 'Thầy Thương Nguyễn',
        email: 'andrewus2015@gmail.com',
        phone: 'Lớp 5A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-5b-01.jpg',
        name: 'HSTT Kathleen Nguyễn',
        email: 'kathleen.phuong.nguyen@hvmatl.org',
        phone: 'Lớp 5B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-5b-02.jpg',
        name: 'HSTT Whitney M. Trần',
        email: 'whitney.tran@hvmatl.org',
        phone: 'Lớp 5B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-5c-01.jpg',
        name: 'HT Kenny Phạm',
        email: 'kenny.pham@hvmatl.org',
        phone: 'Lớp 5C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-5c-02.jpg',
        name: 'Thầy Danny Phi Mai',
        email: 'dannyphimai@gmail.com',
        phone: 'Lớp 5C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-6a-01.jpg',
        name: 'Cô Thùy Linh Hồ',
        email: 'thuy.linh.ho@hvmatl.org',
        phone: 'Lớp 6A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-6a-02.jpg',
        name: 'Thầy Đăng Minh Vũ',
        email: 'danh.minh.vu@hvmatl.org',
        phone: 'Lớp 6A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-6b-01.jpg',
        name: 'HSTT Alex Ngô',
        email: 'alex.ngo@hvmatl.org',
        phone: 'Lớp 6B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-6b-02.jpg',
        name: 'Thầy Tùng Trần',
        email: 'ttran13337@gmail.com',
        phone: 'Lớp 6B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-6c-01.jpg',
        name: 'HT Monica Minh T. Trần',
        email: 'monica.tran@hvmatl.org',
        phone: 'Lớp 6C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-6c-02.jpg',
        name: 'Cô Claire Minh T. Trần',
        email: 'claire.minh.tran@gmail.com',
        phone: 'Lớp 6C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-7a-01.jpg',
        name: 'Thầy Brian H. Nguyễn',
        email: 'brian.hoang.nguyen@hvmatl.org',
        phone: 'Lớp 7A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-7a-02.jpg',
        name: 'HSTT Alex Nguyễn',
        email: 'alex.nguyen@hvmatl.org',
        phone: 'Lớp 7A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-7b-01.jpg',
        name: 'Cô Michelle Vũ',
        email: 'ha.vu012@gmail.com',
        phone: 'Lớp 7B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-7b-02.jpg',
        name: 'Thầy Sơn Trần',
        email: 'tranm2013@gmail.com',
        phone: 'Lớp 7B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-7c-01.jpg',
        name: 'Thầy Bình Phạm',
        email: 'ignatius.binh.pham@hvmatl.org',
        phone: 'Lớp 7C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-7c-02.jpg',
        name: 'Cô Mai Thi Tuyết Lê',
        email: 'mai.tuyet.le@hvmatl.org',
        phone: 'Lớp 7C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-7c-01.jpg',
        name: 'Thầy Bình Phạm',
        email: 'ignatius.binh.pham@hvmatl.org',
        phone: 'Lớp 7D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8a-01.jpg',
        name: 'Cô Loan Vũ',
        email: 'loan.vu@hvmatl.org',
        phone: 'Lớp 8A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8a-02.jpg',
        name: 'HT Michael Nguyễn',
        email: 'michael.duc.nguyen@hvmatl.org',
        phone: 'Lớp 8A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8b-01.jpg',
        name: 'Cô Kas Hồ',
        email: 'kassie.ho@hvmatl.org',
        phone: 'Lớp 8B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8b-02.jpg',
        name: 'HT Hồng Ân Nguyễn',
        email: 'jomar.hongan.nguyen@hvmatl.org',
        phone: 'Lớp 8B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8c-01.jpg',
        name: 'Thầy Hiệp Lê',
        email: 'hiep.le@hvmatl.org',
        phone: 'Lớp 8C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8c-02.jpg',
        name: 'Cô Diễm L. Nguyễn',
        email: 'diem.l.nguyen@hvmatl.org',
        phone: 'Lớp 8C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8d-01.jpg',
        name: 'Thầy Brian Lương',
        email: 'hoangnhut9755@gmail.com',
        phone: 'Lớp 8D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-8d-02.jpg',
        name: 'Cô Thảo Ly Nguyễn',
        email: 'ln3@vmbc.edu',
        phone: 'Lớp 8D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-9a-01.jpg',
        name: 'Thầy Chí Hữu Nguyễn',
        email: 'chi.huu.nguyen@hvmatl.org',
        phone: 'Lớp 9A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-9a-02.jpg',
        name: 'Thầy An Lâm',
        email: 'lamangq74@yahoo.com',
        phone: 'Lớp 9A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-9b-01.jpg',
        name: 'Thầy Bình Trần',
        email: 'binh.tran@hvmatl.org',
        phone: 'Lớp 9B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-9b-02.jpg',
        name: 'Cô Nga Ngọc Nguyễn',
        email: 'nganguyen38@att.net',
        phone: 'Lớp 9B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-9c-01.jpg',
        name: 'Thầy Dũng Anh Nguyễn',
        email: 'dung.anh.nguyen@hvmatl.org',
        phone: 'Lớp 9C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-9d-01.jpg',
        name: 'Cô Diễm L. Nguyễn',
        email: 'diem.l.nguyen@hvmatl.org',
        phone: 'Lớp 9D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-9d-02.jpg',
        name: 'HSTT Quinton Trần',
        email: 'quinton.tran@hvmatl.org',
        phone: 'Lớp 9D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-10a-01.jpg',
        name: 'Cô Hương Kim Vũ',
        email: 'huong.kim.vu@hvmatl.org',
        phone: 'Lớp 10A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-10a-02.jpg',
        name: 'Thầy Eric Trương',
        email: 'eric.truong@hvmatl.org',
        phone: 'Lớp 10A',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-10b-01.jpg',
        name: 'Cô Jacklinh Phạm',
        email: 'maria.jacklinh.nguyen@hvmatl.org',
        phone: 'Lớp 10B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-10b-02.jpg',
        name: 'Cô Hiền Phạm',
        email: 'hien.pham@hvmatl.org',
        phone: 'Lớp 10B',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-10c-01.jpg',
        name: 'Thầy Đức Hữu Nguyễn',
        email: 'duc.huu.nguyen@hvmatl.org',
        phone: 'Lớp 10C',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-10d-01.jpg',
        name: 'Cô Angela Krans',
        email: 'angela.krans@hvmatl.org',
        phone: 'Lớp 10D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-10d-02.jpg',
        name: 'TT Thành Lê',
        email: 'thanh.le@hvmatl.org',
        phone: 'Lớp 10D',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/hs-01-01.jpg',
        name: 'Thầy Khoa Vũ',
        email: 'josephkvu@yahoo.com',
        phone: 'Lớp Hiệp Sĩ 1',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/hs-01-03.jpg',
        name: 'HT Joseph Nguyễn',
        email: 'joseph268@gmail.com',
        phone: 'Lớp Hiệp Sĩ 1',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/hs-02-01.jpg',
        name: 'Cô Hằng Vũ',
        email: 'hang.vu@hvmatl.org',
        phone: 'Lớp Hiệp Sĩ 2',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/hs-02-02.jpg',
        name: 'Thầy James Zahrobsky',
        email: 'jim.zahrobsky.jr@hvmatl.org',
        phone: 'Lớp Hiệp Sĩ 2',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/hs-02-03.jpg',
        name: 'HT Louis Hồ',
        email: 'louis.hieu.ho@hvmatl.org',
        phone: 'Lớp Hiệp Sĩ 2',
    },

    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/giaoly/gl-1a-01.jpg',
        name: 'HT Nguyễn Thu Thảo',
        email: 'thao.thu.nguyen@hvmatl.org',
        phone: 'Thiếu Nhi Thánh Thể 1',
    },
]

export default stJosephTeacherContent;