const VietHongTeacherContent = [
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-duong-hien.jpg',
        name: 'Cô Dương Hiền',
        email: 'hien.duong@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-dao-hoang-phi.jpg',
        name: 'Thầy Đào Hoàng Phi',
        email: 'phi.hoang.dao@hvmatl.org',
    },   
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-dang-kim.jpg',
        name: 'Cô Đặng Kim',
        email: 'kim.dang@hvmatl.org',
    }, 
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-dang-thi-ngoc-dung.jpg',
        name: 'Cô Đặng Ngọc Dung',
        email: 'deedee.dang@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-do-duc-sieu.jpg',
        name: 'Thầy Đỗ Đức Siêu',
        email: 'sieu.duc.do@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-hoang-long.jpg',
        name: 'Thầy Hoàng Tuấn Long',
        email: 'long.tuan.hoang@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.com/gallery/kgd/viethong/vh-23-24-t-huynh-bao-tran.jpg',
        name: 'Cô Huỳnh Bảo Trân',
        email: 'tran.bao.huynh@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-huynh-trang.jpg',
        name: 'Cô Huỳnh Thi Trang',
        email: 'trang.thi.huynh@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-le-bich-duyen.jpg',
        name: 'Cô Lê Bích Duyên',
        email: 'duyen.b.le@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-le-nga.jpg',
        name: 'Cô Lê Nga',
        email: 'nga.le@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-le-steve.jpg',
        name: 'Thầy Lê Steve',
        email: 'steve.le@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nghiem-trang.jpg',
        name: 'Cô Nghiêm Trang',
        email: 'tnghiem@hvmatl.org',
    },    
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-tuong-vy.jpg',
        name: 'Cô Nguyễn Christine',
        email: 'christine.vy.nguyen@hvmatl.org',
    },    
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-a-tuan.jpg',
        name: 'Thầy Nguyễn Anh Tuấn',
        email: 'tuan.nguyen@hvmatl.org',
    },        
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-huu-toan.jpg',
        name: 'Thầy Nguyễn Hữu Toàn',
        email: 'toan.nguyen@hvmatl.org',
    },    
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-alex.jpg',
        name: 'Thầy Nguyễn Joseph Alex',
        email: 'alex.joseph.nguyen@hvmatl.org',
    }, 
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-minh-vien.jpg',
        name: 'Cô Nguyễn Minh Viên',
        email: 'minh-vien.nguyen@hvmatl.org',
    },   
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-chau.jpg',
        name: 'Cô Nguyễn Ngọc Châu',
        email: 'chau.ngoc.nguyen@hvmatl.org',
    },      
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-quoc-tuan.jpg',
        name: 'Thầy Nguyễn Q. Tuấn',
        email: 'tuan.q.nguyen@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-thanh-son.jpg',
        name: 'Thầy Nguyễn T. Sơn',
        email: 'son.thanh.nguyen@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-van.jpg',
        name: 'Cô Nguyễn Thị Vân',
        email: 'van.thi.nguyen@hvmatl.org',
    },  
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-nguyen-thuy-linh.jpg',
        name: 'Cô Nguyễn Thùy Linh',
        email: 'linh.thi.nguyen@hvmatl.org',
    },  
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-ninh-q-dat.jpg',
        name: 'Thầy Ninh Q. Đạt',
        email: 'dat.ninh@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-pham-hong-trung.jpg',
        name: 'Thầy Phạm Hồng Trung',
        email: 'trung.pham@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-pham-t-nga.jpg',
        name: 'Cô Phạm T. Nga',
        email: 'nga.pham@hvmatl.org',
    },   
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-phan-tung.jpg',
        name: 'Cô Phan Tùng',
        email: 'tung.phan@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-tran-jimmy-viet.jpg',
        name: 'Thầy Trần Jimmy Việt',
        email: 'viet.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-tran-lan-binh.jpg',
        name: 'Cô Trần Lan Bình',
        email: 'binh.lan.tran@hvmatl.org',
    },  
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-tran-thanh-truc.jpg',
        name: 'Thầy Trần Thanh Trúc',
        email: 'truc.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-tran-truc-quynh.jpg',
        name: 'Cô Trần Trúc Quỳnh',
        email: 'truc.quynh.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-tran-uyen-chi.jpg',
        name: 'Cô Trần Uyên Chi',
        email: 'uyen.chi.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-vo-mercy-sarah.jpg',
        name: 'Cô Võ Mercy Sarah',
        email: 'sarah.mercy.vo@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-vo-minh-hoang.jpg',
        name: 'Thầy Võ Minh Hoàng',
        email: 'hoang.minh.vo@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-vo-tran.jpg',
        name: 'Cô Võ Tuyết Trân',
        email: 'tran.tuyet.vo@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-t-vu-kim-lien.jpg',
        name: 'Cô Vũ Kim Liên',
        email: 'lien.vu@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-do-mong-lan.jpg',
        name: 'Thầy Đỗ Mộng Lân',
        email: 'lan.mong.do@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-do-minh.jpg',
        name: 'Thầy Đỗ Hoàng Minh',
        email: 'minh.hoang.do@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-la-john.jpg',
        name: 'Thầy La Nhân John',
        email: 'minh.hoang.do@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-le-phuong-dung.jpg',
        name: 'Cô Lê Phương Dung',
        email: 'dung.phuong.le@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-le-thanh-huong.jpg',
        name: 'Cô Lê Thanh Hương',
        email: 'hotrungtran@gmail.com',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-nguyen-john.jpg',
        name: 'Nguyễn John',
        email: 'john.phan.nguyen@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-tran-vinh.jpg',
        name: 'Thầy Trần Vinh',
        email: 'vinh.tran@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-p-vu-khoa.jpg',
        name: 'Thầy Vũ Khoa',
        email: 'khoa.vu@hvmatl.org',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-ai-vy.jpg',
        name: 'Phụ giáo Ái Vy',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-alexander.jpg',
        name: 'Phụ giáo Alexander',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-andrew.jpg',
        name: 'Phụ giáo Andrew',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-cindy.jpg',
        name: 'Phụ giáo Cindy',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-cong-chinh.jpg',
        name: 'Phụ giáo Công Chính',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-dieu-veronica.jpg',
        name: 'Phụ giáo Diệu Veronica',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-gia-kiet.jpg',
        name: 'Phụ giáo Gia Kiệt',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-hong-an.jpg',
        name: 'Phụ giáo Hồng Ân',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-jason.jpg',
        name: 'Phụ giáo Jason',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-pham-katherine.jpg',
        name: 'Phụ giáo Katherine',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-nguyen-khang.jpg',
        name: 'Phụ giáo Nguyên Khang',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-phuong-uyen.jpg',
        name: 'Phụ giáo Phương Uyên',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-quynh-shayla.jpg',
        name: 'Phụ giáo Quỳnh Shayla',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/vh-23-24-ta-tien-dat.jpg',
        name: 'Phụ giáo Tiến Đạt',
    },
]

export default VietHongTeacherContent;