const VietHongTeacherContent = [
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-01-bui-ba-thanh-sh.jpg',
        name: 'Thầy Bùi Bá Thạnh',
        email: 'thanh.ba.bui@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-02-duong-hien.jpg',
        name: 'Cô Dương Hiền',
        email: 'hien.duong@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-03-dao-hoang-phi.jpg',
        name: 'Thầy Đào Hoàng Phi',
        email: 'phi.hoang.dao@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-04-dang-lan.jpg',
        name: 'Cô Đặng Xuân Lan',
        email: 'lan.dang@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-05-do-duc-sieu.jpg',
        name: 'Thầy Đỗ Đức Siêu',
        email: 'sieu.duc.do@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-06-ha-thuy.jpg',
        name: 'Cô Hà Thúy',
        email: 'thuy.ha@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-07-le-bich-duyen.jpg',
        name: 'Cô Lê Bích Duyên',
        email: 'duyen.b.le@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-08-le-bich-hang.jpg',
        name: 'Cô Lê Bích Hằng',
        email: 'hang.b.le@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-09-le-dai-tri.jpg',
        name: 'Thầy Lê Đại Trí',
        email: 'tri.dai.le@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-10-le-steve.jpg',
        name: 'Thầy Lê Steve',
        email: 'steve.le@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-11-ly-thai-truc-ngan.jpg',
        name: 'Cô Lý Thái Trúc Ngân',
        email: 'ngan.thai.ly@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-12-mai-tri-linh.jpg',
        name: 'Cô Mai Trí Linh',
        email: 'linh.tri.mai@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-14-nguyen-huynh-anne.jpg',
        name: 'Cô Nguyễn Huỳnh Anne',
        email: 'anne.nguyen@hvmatl.org',
    },    
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-15-nguyen-huu-duc-sh.jpg',
        name: 'Thầy Nguyễn Hữu Đức',
        email: 'duc.huu.nguyen@hvmatl.org',
    },    
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-16-nguyen-huu-toan.jpg',
        name: 'Thầy Nguyễn Hữu Toàn',
        email: 'toan.nguyen@hvmatl.org',
    },    
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-19-nguyen-trung-minh-vien.jpg',
        name: 'Cô Nguyễn Minh Viên',
        email: 'minh-vien.nguyen@hvmatl.org',
    },       
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-18-nguyen-quoc-tuan.jpg',
        name: 'Thầy Nguyễn Q. Tuấn',
        email: 'tuan.q.nguyen@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-20-nguyen-tung.jpg',
        name: 'Thầy Nguyễn Tùng',
        email: 'tung.nguyen@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-21-ninh-q-dat.jpg',
        name: 'Thầy Ninh Q. Đạt',
        email: 'dat.ninh@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-22-pham-hong-trung.jpg',
        name: 'Thầy Phạm Hồng Trung',
        email: 'trung.pham@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-23-phan-tung.jpg',
        name: 'Cô Phan Tùng',
        email: 'tung.phan@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-24-to-ngoc-quynh-loan.jpg',
        name: 'Cô Tô Ngọc Quỳnh Loan',
        email: 'loan.ngocquynh.to@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-25-tran-huyen.jpg',
        name: 'Cô Trần Huyền',
        email: 'huyen.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-27-tran-jimmy-viet.jpg',
        name: 'Thầy Trần Jimmy Việt',
        email: 'viet.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-28-tran-phung.jpg',
        name: 'Cô Trần Phụng',
        email: 'phung.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-29-tran-thanh-truc.jpg',
        name: 'Thầy Trần Thanh Trúc',
        email: 'truc.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-30-tran-uyen-chi.jpg',
        name: 'Cô Trần Uyên Chi',
        email: 'uyen.chi.tran@hvmatl.org',
    },
    {   
        classification: 'main-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-teacher-31-vo-minh-hoang.jpg',
        name: 'Thầy Võ Minh Hoàng',
        email: 'hoang.minh.vo@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-proctor-01-do-mong-lan.jpg',
        name: 'Thầy Đỗ Mộng Lân',
        email: 'lan.mong.do@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-proctor-02-le-phuong-dung.jpg',
        name: 'Cô Lê Phương Dung',
        email: 'dung.phuong.le@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-proctor-03-le-thanh-huong.jpg',
        name: 'Cô Lê Thanh Hương',
        email: 'hotrungtran@gmail.com',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-proctor-04-tran-vinh.jpg',
        name: 'Thầy Trần Vinh',
        email: 'vinh.tran@hvmatl.org',
    },
    {   
        classification: 'main-proctor',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-proctor-05-vu-khoa.jpg',
        name: 'Thầy Vũ Khoa',
        email: 'khoa.vu@hvmatl.org',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-01-do-thanh-thu-vivian.jpg',
        name: 'Đỗ Thanh Thư Vivian',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-02-le-hoang-pham-hong-an.jpg',
        name: 'Lê Hoàng Hồng Ân',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-03-le-minh-ngoc-lisa.jpg',
        name: 'Lê Minh Ngọc Lisa',
    },    
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-06-le-tri-dung-benjamin.jpg',
        name: 'Lê Trí Dũng Benjamin',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-07-nguyen-doan-han.jpg',
        name: 'Nguyễn Đoàn Hân',
    }, 
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-08-nguyen-thien-an-chloe.jpg',
        name: 'Nguyễn Thiên An Chloe',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-09-pham-katherine.jpg',
        name: 'Phạm Katherine',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-10-pham-long-jimmy.jpg',
        name: 'Phạm Long Jimmy',
    }, 
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-11-tran-lu-christina.jpg',
        name: 'Trần Lu Christina',
    },
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-14-tran-xuan-sang.jpg',
        name: 'Trần Xuân Sang',
    }, 
    {   
        classification: 'assistant-teacher',
        image: 'https://hvmatl.net/gallery/kgd/viethong/viethong-2020-2021-ta-13-vu-ngoc.jpg',
        name: 'Vũ Ngọc',
    }, 
]

export default VietHongTeacherContent;