const vnSaintsTOC = [
    {
        day:'NGÀY THỨ NHẤT',
        link:'1',
        prayerName: 'Kính Thánh Anê Lê Thị Thành',
        name: 'ANÊ LÊ THỊ THÀNH',
        birthDeath: '1781-1841',
        song: `1. Cầu xin Chúa Thánh Thần. Người thương thăm viếng hồn con. Ban xuống cho con hồng ân chan chứa. Trau dồi cho đáng ngôi thánh đường.\nĐK: Nguyện xin Chúa Ngôi Ba. Đoái nghe lời con thiết tha. Tình thương mến ấp ủ con ngày đêm. Nhuần thấm xác hồn tràn lan ơn thiêng.`,
        introduction: `Anh chị em thân mến, Giáo Hội Việt Nam rất vui mừng vì có 118 vị Thánh Tử Đạo. Trong hàng ngũ các ngài, ngoài các vị là Giám Mục, Linh Mục, Phó Tế, Thầy Giảng thì đa số là giáo dân. Ơn Chúa đã giúp các ngài can đảm làm chứng cho Tin Mừng Đức Kitô. Các thánh đã bền vững đến cùng trong lòng tin vào Chúa, nêu gương sáng cho cháu con hôm nay. Là con cháu và được kế thừa gia sản đức tin của các Thánh Tử Đạo, chúng ta cùng chiêm ngắm, học hỏi và chia sẻ gương sống đạo của các Thánh Tử Đạo Việt Nam. Hôm nay ngày đầu tiên trong tuần cửu nhật, chúng ta tìm hiểu về cuộc đời vị thánh nữ Anê Lê Thị Thành.`,
        title1: 'Thánh nữ tiên khởi Việt Nam',
        story1:'Nhìn lại lịch sử Giáo Hội Công Giáo Việt Nam, số chị em phụ nữ góp phần xương máu làm chứng đức tin không phải là ít. Tuy nhiên tinh thần kiên cường bất khuất vì đức tin Kitô giáo của thánh nữ Anê Lê Thị Thành là một mẫu gương hiếm có. Chính quan tổng đốc Trịnh Quang Khanh nổi tiếng "hùm xám tỉnh Nam"cũng đành phải bất lực trong việc thuyết phục bà chối đạo. Quan áp dụng nhiều phương thế, từ khuyên dụ ngon ngọt đến tra tấn nhục hình, gông xiềng, đòn đánh đến tan nát thân mình, cũng không thể lung lạc đức tin trung kiên của thánh nữ. Những giọt máu tung tóe vì đòn vọt đã trở nên những bông hoa hồng kết thành triều thiên tử đạo, phần thưởng tuyệt hảo Thiên Chúa trọng thưởng: Anê Lê Thị Thành, thánh nữ tiên khởi của Giáo Hội Công Giáo Việt Nam.',
        title2: 'Người mẹ gương mẫu',
        story2: 'Anê Lê thị Thành sinh tại Thanh Hóa. Ngay từ nhỏ, cô Thành đã theo mẹ về quê ngoại ở Phúc Nhạc, một giáo xứ lớn nay thuộc giáo phận Phát Diệm, tỉnh Ninh Bình. Năm 17 tuổi cô kết hôn với người cùng xã, và sống với nhau rất hạnh phúc, thuận hòa sinh hạ 6 người con. Tục lệ địa phương thường gọi tên cha mẹ bằng tên người con đầu lòng, vì thế mới có tên bà Đê. Hai ông bà sống hiền lành đạo đức, rất quan tâm đến việc giáo dục con cái. Cô Lucia Nụ, con gái út khai cung khi giáo quyền thẩm vấn trong việc điều tra phong thánh như sau :\n"Thân mẫu chúng tôi rất chăm lo việc giáo dục chúng tôi. Chính người dạy chúng tôi học chữ và giáo lý, sau dạy cách tham dự thánh lễ và xưng tội rước lễ. Người không để chúng tôi biếng nhác việc xưng tội. Khi chúng tôi lơ là, người thúc dục chúng tôi bằng được mới thôi. Người cho chúng tôi nhập hội con Đức Mẹ, vào ban thiếu nữ thưa kinh ở nhà thờ."\nMột người con khác, cô Anna Năm cũng xác minh : "Song thân chúng tôi chỉ gả con gái cho những thanh niên đạo hạnh. Sau khi tôi kết hôn thân mẫu thường đến thăm chúng tôi và khuyên bảo những điều tốt lành. Có lần người dạy tôi: Tuân theo ý Chúa, con lập gia đình là gánh rất nặng. Con phải ăn ở khôn ngoan, đừng cãi lời cha mẹ chồng. Hãy vui lòng đón nhận Thánh Giá Chúa gởi cho. Người cũng thường khuyên vợ chồng tôi : "Hai con hãy sống hòa hợp, an vui, đừng để ai nghe chúng con cãi nhau bao giờ."',
        title3: 'Từ bác ái đến tử đạo',
        story3: 'Ông bà Đê có lòng bác ái hay thương giúp đỡ người, nhất là trọng kính và sốt sắng giúp đỡ các linh mục gặp khó khăn trong thời cấm đạo. Ông bà dành một khu nhà đặc biệt để các linh mục thừa sai trú ẩn. Chính đức ái đó đã đưa bà Đê đến phúc Tử Đạo.\nSáng ngày lễ phục sinh năm 1841. Quan truyền tập trung giáo dân lại để quân lính lục soát từng nhà. Bà cũng bị bắt. Tất cả bị trói mang gông điệu ra đình làng. Nhà bà bị lục soát, thóc lúa, đồ dùng, tiền bạc đều bị lính lấy hết. Khi bị bắt, bà rất sợ hãi, nhưng khi bị điệu ra đình làng thì gương mặt bà vui tươi và không có vẻ gì là sợ sệt nữa.',
        title4: 'Mặc áo hoa hồng',
        story4: 'Các quan truyền đánh đòn bà. Lúc đầu lính đánh bằng roi, sau dùng củi lớn quật vào chân bà. Khi chồng bà đến thăm, bà giải thích vì sao bà kiên tâm như vậy: "Họ đánh đập tôi vô cùng hung dữ, đến đàn ông còn không chịu nổi, nhưng tôi đã được Đức Mẹ giúp sức, nên tôi không cảm thấy đau đớn."\nLần tiếp theo ra trước tòa, quan cho túm tay áo lại rồi thả rắn độc vào trong áo, nhưng bà Đê vẫn giữ được bình tĩnh cách lạ lùng. Bà đứng yên không hề nhúc nhích nên rắn không cắn, chỉ lượn vài vòng rồi bò ra. Các quan truyền đánh bà dữ hơn nữa rồi giam trong ngục. Nhưng bà đã kiệt sức, đi không nổi.\nCô Lucia Nụ, đến thăm mẹ trong ngục, thấy y phục thân mẫu loang lỗ máu, cô thương mẹ khóc nức nở, bà an ủi con bằng những lời tràn trề lạc quan: "Con đừng khóc nữa, mẹ mặc áo hoa hồng đấy, mẹ vui lòng chịu khổ vì Chúa Giêsu, sao con lại khóc?"\nCuối cùng bà dâng lời sau hết: "Giêsu Maria Giuse! Con xin phó linh hồn và thân xác con trong tay Chúa, xin ban ơn để con tuân theo ý Chúa trong mọi sự." Bà Anê Đê đã về Cha trên trời trong tinh thần thánh thiện ấy. Hôm đó là ngày 12.07.1841, sau ba tháng bị giam cầm vì đức tin. Bà hưởng thọ 60 tuổi.',
        psalmNumber: '41 (42)',
        psalmResponse: 'Lạy Chúa, bao giờ con được đến vào bệ kiến Tôn Nhan!',
        psalm1: 'Như nai rừng mong mỏi\ntìm về suối nước trong,\nhồn con cũng trông mong\nđược gần Ngài, lạy Chúa.\n\nLinh hồn con khao khát Chúa Trời,\nlà Chúa Trời hằng sống.*\nBao giờ con được đến\nvào bệ kiến Tôn Nhan?\n\nChâu lệ là cơm bánh đêm ngày,\nkhi thiên hạ thường ngày cứ hỏi:\nnày Thiên Chúa ngươi đâu?"\n\nTôi thả hồn miên man tưởng nhớ\nthuở tiến về lều thánh cao sang\nđến tận nhà Thiên Chúa,*\ncùng muôn tiếng reo mừng tán tạ,\ngiữa sóng người trẩy hội tưng bừng.\n\nHồn tôi hỡi, cớ sao phiền muộn,\nxót xa phận mình mãi làm chi?\nHãy cậy trông Thiên Chúa,\ntôi còn tán tụng Người,\nNgười là Ðấng cứu độ,\nlà Thiên Chúa của tôi.\n',
        psalm2: 'Lạy Chúa, con chìm sâu trong phiền muộn,*\nnên chi từ giải đất Gio-đan,\ncũng như rặng Khe-mon cao ngất, và núi nhỏ Mi-xa,\ncon tưởng nhớ đến Ngài.\n\nKìa vực thẳm kêu gào vực thẳm,\nkhi tiếng thác của Ngài tuôn đổ ầm vang.*\nSóng cồn theo nước cuốn,\nNgài để cho tràn ngập thân này.\n\nBan ngày Chúa gửi tình thương xuống,*\ncon ngâm nga bài thánh nhạc thâu đêm\nthành kinh nguyện dâng Chúa Trời nguồn sống.\n\nCon thưa cùng Thiên Chúa,\nlà núi đá bảo vệ đời con: "Chúa quên con sao đành?*\nSao con phải lang thang tiều tụy,\nbị quân thù áp bức mãi không thôi ?"\n\nXương cốt con gãy rời từng khúc,\nbởi đối phương lăng nhục thân này,*\nkhi thiên hạ thường ngày cứ hỏi:\n"Này Thiên Chúa ngươi đâu?"\n\nHồn tôi hỡi, cớ sao phiền muộn,\nxót xa phận mình mãi làm chi?\nHãy cậy trông Thiên Chúa,\ntôi còn tán tụng Người,\nNgười là Ðấng cứu độ,\nlà Thiên Chúa của tôi.\n\nVinh danh Chúa Cha và Chúa Con\ncùng vinh danh Thánh Thần Thiên Chúa.\nTừ muôn đời và chính hiện nay,\nluôn mãi tới thiên thu vạn đại, Amen.',
        chVerse: 'Rm 8:35-39',
        reading: 'Lời Chúa trong thư của thánh Phaolô tông đồ gửi tín hữu Rôma.\nAnh em thân mến, ai có thể tách chúng ta ra khỏi tình yêu của Ðức Kitô? Phải chăng là gian truân, khốn khổ, đói rách, hiểm nguy, bắt bớ, gươm giáo? Như có lời chép: Chính vì Ngài mà mỗi ngày chúng con bị giết, bị coi như bầy cừu để sát sinh. Nhưng trong mọi thử thách ấy, chúng ta toàn thắng nhờ Ðấng đã yêu mến chúng ta. Ðúng thế, tôi tin chắc rằng: Cho dù là sự chết hay sự sống, thiên thần hay ma vương quỷ lực, hiện tại hay tương lai. Hoặc bất cứ sức mạnh nào, trời cao hay vực thẳm, hay bất cứ một loài thọ tạo nào khác, không có gì tách được chúng ta ra khỏi tình yêu của Thiên Chúa thể hiện nơi Ðức Giêsu Kitô, Chúa chúng ta.',
        prayerResponse: 'Chúng con cầu xin Chúa.',
        prayer1: '1. Lạy Chúa, Chúa đã ban cho Các Thánh Tử Đạo Việt Nam lòng can trường và mến yêu Chúa mãnh liệt. Nhờ đó các ngài đã dám sống đến cùng ơn gọi Kitô hữu trong mọi hoàn cảnh khó khăn nguy hiểm.\n- Xin cho chúng con cũng biết noi gương các ngài sống tận hiến đời mình cho đức tin.',
        prayer2: '2. Lạy Chúa, sự hy sinh của Các Thánh Tử Đạo Việt Nam, cho thấy tình yêu mạnh hơn sự chết và chết là cửa mở vào cõi sống bất diệt.\n- Xin cho những bạn trẻ trong Giáo Xứ, cũng biết can đảm làm chứng cho Chúa trong mọi hoàn cảnh sống của mình.',
        prayer3: '3. Lạy Chúa, ngọn lửa đức tin mà các Thánh Tử Đạo Việt Nam đã thắp lên bằng cuộc sống và cái chết, được bừng tỏa trên Tổ Quốc Việt Nam.\n- Xin cho dòng máu thắm của các ngài, được thấm vào mảnh đất quê hương để công cuộc truyền giáo được sinh nhiều hoa trái.',
        prayer4: '4. Trên thiên quốc, Các Thánh Tử Đạo Việt Nam đang được hưởng niềm hạnh phúc bất diệt Chúa hứa ban.\n- Xin Các Thánh cũng cầu bầu cùng Chúa cho các linh hồn còn trong vòng thanh luyện, sớm được hưởng hạnh phúc quê trời cùng các ngài.',
        para1: 'Lạy Chúa Giêsu Kitô, xưa Các Thánh Tử Đạo Việt Nam đã theo gương Chúa mà anh dũng hy sinh cuộc đời, dâng hiến máu đào làm chứng cho Phúc Âm. Xin giúp chúng con hôm nay cũng biết can đảm, hy sinh sống theo Phúc Âm, để làm chứng cho Chúa trong đời sống hằng ngày. Chúa là Đấng hằng sống và hiển trị muôn đời. Amen.',
        para2: 'Lạy Các Thánh Tử Đạo Việt Nam, là con thảo của Cha trên trời, là chứng nhân anh dũng của Chúa Kitô, là thành phần trung kiên của Hội Thánh. Nay chúng con xin hợp với các Ngài, và với Đức Trinh nữ Maria, là nữ vương Các Thánh Tử Đạo, mà ca tụng Chúa muôn trùng cao cả. Xưa Chúa ban cho các Ngài được vững tin vào lời Chúa, và đầy sức mạnh của Thánh Thần, nên các Ngài đã kiên tâm chịu gian lao đau khổ, quyết một lòng theo Đức Kitô trên con đường Thập Giá và hy sinh đến giọt máu cuối cùng. Các Ngài đã chấp nhận nên hạt lúa gieo vào lòng đất, để Hội Thánh Việt Nam thu lượm được một mùa lúa dồi dào. Nay Hội Thánh lại dâng các Ngài lên Chúa, như hoa quả đầu mùa để cảm tạ tri ân. Các Ngài đã yêu mến quê hương, xin cầu cho Đất Nước được an vui hạnh phúc, và góp phần xây dựng một thế giới hòa bình. Các Ngài đã cam lòng chịu chết mà không oán hận, xin cầu cho đồng bào mọi giới biết yêu thương đùm bọc lẫn nhau. Các Ngài đã hy sinh tất cả vì đức tin, xin cầu cho mọi Kitô hữu biết sống và chia sẻ niềm tin của mình. Lạy Các Thánh Tử Đạo Việt Nam, là những bậc tiền nhân đã hoàn thành sứ mạng, xin chuyển cầu cho chúng con là con cháu được noi gương các Ngài, biết đem lòng bác ái dấn thân vào phục vụ, để một ngày kia trên thiên quốc, chúng con được hợp tiếng với các Ngài, ca tụng tạ ơn Chúa muôn đời vinh hiển. Amen.'
    },
]

export default vnSaintsTOC